### ISSUE TITLE
EMA notifications don't appear on MS Band

### ISSUE THREAD

**Issue by ssamiei** [MD2Korg/mCerebrum-MicrosoftBand#3]
When setting up a band (setting L/R wrist placement), the MicrosoftBand app crashes upon saving. Despite this, the MS Band background successfully configures to the setting (left - green or blue - right), but the extra tiles do not show up and EMA notifications only cause the Band to vibrate -- no notification appears on the MS Band screen.

**Comment by ssamiei** [comment]
Problem appeared to be corrected in version 0.2.1. Using version 0.2.2, the MS Band 2 will vibrate but no notification shows up on a Band that has not been previously configured with mCerebrum.

**Comment by twhnat** [comment]
@ssamiei Is this still a problem with the current version of the software?

**Comment by ssamiei** [comment]
Yes: Band vibrates but no notifications show up on the Band touchscreen.

**Comment by twhnat** [comment]
@ssamiei is this still a problem?

**Comment by ssamiei** [comment]
The problem is resolved with update to latest applications and configuration files.
